name: Python Application Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x' 

    - name: Check out code
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: List test files
      run: ls -l tests/

    - name: Run unit tests
      run: python -m unittest tests/test_cafetera.py
